Error on Netdis GP for graphs with a number of connected nodes smaller than 5 (default binning requirement of the number of egos per bin). Error obtained before:
Error: node stack overflowError during wrapup: node stack overflow

This was caused by binning_fn in the call:

binned_densities <- binning_fn(densities)

The function binned_densities_adaptive has been modified to account for this possibility.